# Generated by Django 4.1.1 on 2022-09-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.TextField(max_length=1000, null=True, verbose_name='Language'),
        ),
    ]
